export const products = [
  {
    name: 'Starter Backpack',
    imageUrl: 'https://example.com/images/backpack.jpg',
    price: 29.99,
    stock: 50,
    description: 'A simple starter backpack for every adventurer.',
  },
  {
    name: 'Warrior Shield',
    imageUrl: 'https://example.com/images/shield.jpg',
    price: 89.5,
    stock: 20,
    description: 'Heavy shield for maximum protection in battle.',
  },
  {
    name: 'Magic Wand',
    imageUrl: 'https://example.com/images/wand.jpg',
    price: 120,
    stock: 15,
    description: 'Casts powerful spells. Suitable for mage class.',
  },
  {
    name: 'Healing Potion',
    imageUrl: 'https://example.com/images/potion.jpg',
    price: 9.5,
    stock: 200,
    description: 'Restores 50 HP instantly.',
  },
  {
    name: 'Leather Boots',
    imageUrl: 'https://example.com/images/boots.jpg',
    price: 45.0,
    stock: 35,
    description: 'Increases movement speed by 10%.',
  },
  {
    name: 'Iron Sword',
    imageUrl: 'https://example.com/images/sword.jpg',
    price: 75,
    stock: 25,
    description: 'Reliable melee weapon with decent damage.',
  },
  {
    name: 'Archer’s Bow',
    imageUrl: 'https://example.com/images/bow.jpg',
    price: 85,
    stock: 18,
    description: 'Perfect for long-range attacks.',
  },
  {
    name: 'Explorer’s Map',
    imageUrl: 'https://example.com/images/map.jpg',
    price: 15,
    stock: 100,
    description: 'Shows hidden locations and treasures.',
  },
  {
    name: 'Fire Scroll',
    imageUrl: 'https://example.com/images/scroll.jpg',
    price: 60,
    stock: 40,
    description: 'Deals fire damage to all nearby enemies.',
  },
  {
    name: 'Gemstone Ring',
    imageUrl: 'https://example.com/images/ring.jpg',
    price: 150,
    stock: 5,
    description: 'Increases magic power by 20%.',
  },
];
